.pre-commit-config.yaml
README.md
chromadb_hfds/__main__.py
chromadb_hfds/chroma_import.py
poetry.lock
pyproject.toml

- Update README.md with up-to-date info
- Added command script `chromadb-hfds`
- Improved ImportRequest for better readability
- Added pre-commit hooks for linting
Refs: #1

feat: Added typer support

---

README.md
chroma_dp/huggingface/__init__.py
chroma_dp/huggingface/hf_export.py
chroma_dp/main.py
chroma_dp/utils/chroma.py
pyproject.toml

- import private and public datasets
- export private and public datasets
- Updated README.md
Refs: #2, #3

feat: Export

---

README.md
chroma_dp/chroma/chroma_import.py
chroma_dp/huggingface/__init__.py
chroma_dp/processor/embed.py
chroma_dp/utils/embedding.py
docs/index.md
docs/processors/embedding.md

feat: Added openai EF support

---

README.md
chroma_dp/__init__.py
chroma_dp/chroma/chroma_export.py
chroma_dp/huggingface/__init__.py
chroma_dp/processor/chunk.py
chroma_dp/producer/file/pdf.py
chroma_dp/utils/chroma.py
chroma_dp/utils/embedding.py
docs/index.md
docs/processors/embedding.md
tests/hf/test_uri.py

- Did a bit of cleanup on imports
- Set chunker separator to \n (need to make this configurable via option)
- Updated docs
Refs: #25

feat: Added HF embedding function support

---

.pre-commit-config.yaml
chroma_dp/huggingface/utils.py
chroma_dp/utils/embedding.py
docs/processors/embedding.md
pyproject.toml
tests/hf/test_hf_export.py
tests/hf/test_hf_import.py

- Removed mypy.ini and moved it in pyproject.toml
- Cleaned up HF tests, need to be redone
- Updated documentation
Refs: #26

feat: Sentence Transformers HF support

---

chroma_dp/processor/chunk.py

feat: Added separator with default new line to the chunk processor

---

chroma_dp/main.py
chroma_dp/processor/misc/emoji_clean.py
chroma_dp/producer/file/pdf.py
chroma_dp/producer/url/url_loader.py
docs/processors/cleaning.md
docs/producers/url.md

- Ability to import a single page or recursively load a website
- Added emoji cleaner processor
- Docs updated
Refs: #48, #49

feat: URL generator

---

.dockerignore
.github/workflows/build-images.yml
Dockerfile
poetry.lock
pyproject.toml

feat: Dockerfile

---

chroma_dp/main.py
chroma_dp/producer/file/text.py
docs/producers/text.md
sample-data/text/about.md
sample-data/text/api-reference.md
sample-data/text/contributing.md
sample-data/text/deployment.md
sample-data/text/embeddings.md
sample-data/text/getting-started.md
sample-data/text/integrationsold.md
sample-data/text/intro.md
sample-data/text/migration.md
sample-data/text/multi-modal.md
sample-data/text/observability.md
sample-data/text/production.md
sample-data/text/roadmap.md
sample-data/text/telemetry.md
sample-data/text/troubleshooting.md
sample-data/text/usage-guide.md

feat: Text file generator support

---

README.md
chroma_dp/main.py
docs/adr/ADR-20240120-CLI-Naming.md
docs/index.md
docs/processors/chunking.md
docs/processors/embedding.md
docs/producers/text.md
docs/producers/url.md

Renamed commands for ecosystem alignment
Refs: #39

feat: ADR-20240120-CLI-Naming

---

README.md
chroma_dp/chroma/chroma_export.py
chroma_dp/chroma/chroma_import.py
docs/index.md

URIs are now the only argument for import and export commands
Refs: #56

feat: Removed --uri options for cdp import

---

README.md
chroma_dp/chroma/chroma_import.py
chroma_dp/huggingface/__init__.py
chroma_dp/huggingface/utils.py
docs/index.md

feat: Removed --uri options for HF commands

---

.github/workflows/cdp-action-test.yaml
.gitignore

feat: GH Workflow to test the action

---

chroma_dp/chroma/chroma_import.py
chroma_dp/utils/__init__.py
chroma_dp/utils/chroma.py

feat: Distance function is now supported when importing

---

README.md
chroma_dp/chroma/chroma_export.py
chroma_dp/chroma/chroma_import.py
docs/index.md

feat: Added where filter to export command

---

README.md
docs/index.md

docs: Added example use cases

---

chroma_dp/chroma/chroma_import.py

feat: Added multi-threading support to import cmd

---

chroma_dp/chroma/chroma_export.py

feat: where document filter in export command

---

chroma_dp/utils/chroma.py

fix: added selecting default metadata if none is provided

---

chroma_dp/main.py
chroma_dp/processor/id.py
docs/processors/id.md
docs/processors/metadata.md
poetry.lock
pyproject.toml

feat: ID Generator Strategies

---

chroma_dp/chroma/chroma_import.py

fix: Indentation issue in chroma import command

---

chroma_dp/main.py
chroma_dp/producer/file/csv.py
docs/producers/csv.md
sample-data/csv/employees_with_resumes.csv

feat: CSV generator

---

chroma_dp/chroma/chroma_export.py
chroma_dp/chroma/chroma_import.py
chroma_dp/huggingface/__init__.py
chroma_dp/processor/chunk.py
chroma_dp/processor/embed.py
chroma_dp/processor/id.py
chroma_dp/processor/langchain_utils.py
chroma_dp/processor/metadata.py
chroma_dp/processor/misc/emoji_clean.py
chroma_dp/producer/file/csv.py
chroma_dp/producer/file/pdf.py
chroma_dp/producer/file/text.py
chroma_dp/producer/url/url_loader.py
poetry.lock
pyproject.toml

feat: orjson serialization and deserialization

---

chroma_dp/chroma/chroma_import.py
chroma_dp/main.py
chroma_dp/utils/chroma.py
chroma_dp/utils/embedding.py
docs/index.md
docs/processors/embedding.md

feat: Importing metadata from ebeddable resource

---

chroma_dp/processor/metadata.py
docs/processors/metadata.md
tests/processors/test_metadata.py

- Added tests for metadata
Refs:  #119, #15

feat: Renamed flags for metadata

---

chroma_dp/chroma/chroma_export.py

feat: Chroma export formats

---

pyproject.toml

Also bumping chroma version to 0.4.24

feat: release/0.0.8

---

chroma_dp/chroma/chroma_export.py

Closes #147
feat: Adding thread pool for speedier exports
feat: Improved streaming and made thread count configurable with default to 1

feat: Adding thread pool for speedier exports

---

chroma_dp/utils/embedding.py
docs/processors/embedding.md

feat: Ollama Embeddings

---

chroma_dp/__init__.py
pyproject.toml

Making chromadb package optional dependency

---

chroma_dp/__init__.py
chroma_dp/chroma/chroma_import.py
chroma_dp/utils/chroma.py
docs/index.md

feat: Support numpy-based Chroma embeddings
